### ISSUE TITLE
Non Consistent Education Status

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#60]
https://github.com/SAY-DAO/backend/blob/71209e24ac801c79ac3dc02d8b78f0f4527183c0/say/models/child_model.py#L71

 Some of our children have education status which is out of range of the suggested above:

example=> Child:39 And Education:96

**Comment by iRhonin** [comment]
I think @Elhamne knows more about this.

**Comment by Elhamne** [comment]
Hi @ehsan-g 
At the legacy panel client we have two fields for education: `Education status` and `School Type`. Education consists of these two.
 The agreement on the education code used to be as follow:

If education number has 2 or more than 2 digits **and** the first digit is **6, 7, 8, or 9**:
```
- 6: school for the deaf
- 7: School for the blind
- 8: Intellectual disabilities school
- 9: school
```

The rest of the digits will mean the comment you've mentioned.
In your example, child 39 education is  _6th grade at an ordinary school_.

### BUT
A couple of months ago I figured out that the social workers didn't choose **the school type** or selected it wrong. 
So this field's information is not reliable. Also, it won't update by itself. 

I talked to @Nedapapen about it and we decided to remove this field temporarily. And she said they don't need this field at this time and they're already getting the information from the **info** field. Since we could make this field more reliable and automatic.

**Comment by ehsan-g** [comment]
@Elhamne  Thanks for clarifying
